mqtt:
  enabled: false
tls:
  enabled: false
auth:
  reset_admin_password: true
cameras:
  dummy_camera: # <--- this will be changed to your actual camera later
      enabled: false
      ffmpeg:
        hwaccel_args: preset-vaapi
        inputs:
          - path: rtsp://127.0.0.1:554/rtsp
            roles:
              - detect
version: 0.15-1
camera_groups: {}