#!/command/with-contenv bash
set -euo pipefail

# Wait for the config file to exist
while [ ! -f /tmp/frigate/config.yaml ]; do
  sleep 1
done

# Watch for modifications
inotifywait -m -e modify /tmp/frigate/config.yaml |
while read -r _; do
  echo "[INFO] Detected config.yaml change, restarting frigate..."
  s6-rc -a change frigate
done
